### ISSUE TITLE
livesync vs run display differently on iOS simulator

### ISSUE THREAD

**Issue by alexziskind1** [TheOriginalJosh/nativescript-weather#7]
When I run `>tns run ios --emulator` it looks like this (notice the back button is there and refresh is not, the labels don't wrap and the font is black)

<img width="487" alt="screen shot 2016-07-09 at 3 59 56 pm" src="https://cloud.githubusercontent.com/assets/1638579/16709981/341ce7a6-45ee-11e6-8e7e-642efc37a9fe.png">

When I run `>tns livesync ios --emulator --watch` it looks like this:

<img width="487" alt="screen shot 2016-07-09 at 4 00 51 pm" src="https://cloud.githubusercontent.com/assets/1638579/16709985/51be63d4-45ee-11e6-817b-5d339ad831b3.png">

**Comment by JoshDSommer** [comment]
Hey @alexziskind1  thanks for the feedback man. I think this is related to the router issues i mentioned on slack the other day... still trying to figure out if i can fix it my self or if i'll have to wait until the next release.

**Comment by JoshDSommer** [comment]
I spoke to @NathanWalker and i guess this is a known issues with livesync right now. :\
