### ISSUE TITLE
Choose Postal Code from results (2 or more)

### ISSUE THREAD

**Issue by leocaseiro** [TheOriginalJosh/nativescript-weather#8]
Hi @TheOriginalJosh, I'm testing this app in Australia, and I searched my postal code which is `2452`. However, my result is the third one from the [GMaps Api](https://maps.googleapis.com/maps/api/geocode/json?address=&components=postal_code:2452&sensor=false). With that said, I'm not able to select my current location. Only Bulgaria. But that's not what I need LOL.

That would be nice if the results would show as a list to choose the right city instead of assuming will always be the first result.

I'm happy to send you a PR, please let me know your thoughts.

Thanks.

**Comment by JoshDSommer** [comment]
Hey @leocaseiro  thanks for the heads up on this man. what i've end up doing is adding the ability to specify the country to with the postal code in in your case it would be '2452 AU`  to get the right location.  

That make sense... for some reason _cough_ cough_ angular router didn't like me out putting a list and this seemed like a easy work around with out me pulling out more of my hair. 

Let me know what you think man :)

**Comment by leocaseiro** [comment]
Hi @TheOriginalJosh. Perfect, I didn't know I could type extra parameters.

That works great. `2452 AU`

Cheers

**Comment by leocaseiro** [comment]
Hi @TheOriginalJosh, I've just realised that won't work for the next city.

It's called Coffs Harbour:  https://maps.googleapis.com/maps/api/geocode/json?address=coffs+harbour&components=postal_code

However, If I search by postal_code=2450, it doesn't come up:
https://maps.googleapis.com/maps/api/geocode/json?address=&components=postal_code:2450+au

Perhaps we could have an option to type address or postal_code. I'm not sure if it'll work for you.

**Comment by JoshDSommer** [comment]
No worries... I have a small update coming that will update the api so search for 

https://maps.googleapis.com/maps/api/geocode/json?address=&components=postal_code:2450,country:au 

instead of the +au 

I just keep breaking things in the process. Thanks for all your help man I appreciate it 👍

**Comment by leocaseiro** [comment]
I see, but I can't find [Coffs Harbour](https://www.google.com.au/maps/place/Coffs+Harbour+NSW/@-30.2823966,152.9263827,12z/data=!4m5!3m4!1s0x6b9c0e4e8be97c93:0x40609b490439470!8m2!3d-30.2986482!4d153.109417) still. It's weird, but this search result another area near by, called [Upper Orara](https://www.google.com.au/maps/place/Upper+Orara+NSW+2450/@-30.2823966,152.9263827,12z/data=!3m1!4b1!4m5!3m4!1s0x6b9c1ae037f41fbf:0x40609b490439a60!8m2!3d-30.277229!4d152.9912281) which is a different area the one I need.
